# Este docker compose teve como base o da rinha de backend 2024 q1.
version: "3.5"

services:
  api01: &api
    image: minha-api-matadora:latest
    build: .
    hostname: api01
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rinha
      - DB_USER=admin
      - DB_PASS=123
    
    ports:
      - "8081:8080"
    restart: on-failure:10
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "130MB"
    networks:
      - rinha-nginx-2024q1

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api 
    hostname: api02
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=rinha
      - DB_USER=admin
      - DB_PASS=123
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "90MB"
    networks:
      - rinha-nginx-2024q1

  db:
    image: postgres:15.6-alpine3.19
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin" ]
      timeout: 40s
      interval: 2s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: "0.63"
          memory: "120MB"
    networks:
      - rinha-nginx-2024q1


networks:
  rinha-nginx-2024q1:
    driver: bridge
    name: rinha-nginx-2024q1
    external: true

  # Outra forma de configurar a rede seria da forma abaixo. Seria necessário remover a rede dos services.
  # default:
  #   driver: bridge
  #   name: rinha-nginx-2024q1
  #   name: host
  #   external: true